version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8001:8080"
    networks:
      - app-network
    depends_on:
      - db

  wallet-service:
    build:
      context: ./wallet-service
    ports:
      - "8002:8080"
    networks:
      - app-network
    depends_on:
      - db

  user-service:
    build:
      context: ./user-service
    ports:
      - "8003:8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_panel
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db-data:


  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - app-network
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
    networks:
      - app-network
    command: server /data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network


  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - app-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf


  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - app-network
