# docker-compose.yml

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_db_username
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRY=1h

volumes:
  db-data:
