version: '3.8'

services:
  companies-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://ehsansobhani:01361015@db:5432/transport?sslmode=disable
      - PORT=3001
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ehsansobhani
      POSTGRES_PASSWORD: 01361015
      POSTGRES_DB: transport
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ehsansobhani"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

