
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "microservices"
    static_configs:
      - targets: ['auth-service:8080', 'wallet-service:8080', 'user-service:8080']
  - job_name: "api-gateway"
    static_configs:
      - targets: ['api-gateway:10000']
